"""Read-only qualification of Test 1 thermostat temperature semantics.

Run in VEScripts with the generated Test 1 project open.  The probe reads the
Apache engine input generated by the latest preprocessing/simulation.  It does
not edit the VE model, Apache input or APS result.
"""

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import iesve


ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

REQUIRED_RFCONT = 0.5


def _write_json(path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, default=str) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def _read_rfcont(project_root):
    apache_dir = project_root / "apache"
    preferred = apache_dir / "{}.der".format(project_root.name)
    candidates = [preferred] if preferred.is_file() else sorted(apache_dir.glob("*.der"))
    if len(candidates) != 1:
        return None, None, (
            "Expected exactly one generated .der file in {}; found {}"
            .format(apache_dir, len(candidates))
        )
    path = candidates[0]
    try:
        text = path.read_text(encoding="latin-1")
    except OSError as exc:
        return path, None, str(exc)
    match = re.search(
        r"(?mi)^\s*RFCONT\s*,\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][-+]?\d+)?)\s*,?",
        text,
    )
    if match is None:
        return path, None, "RFCONT was not found"
    return path, float(match.group(1)), ""


def run():
    project = iesve.VEProject.get_current_project()
    project_root = Path(str(project.path)).resolve()
    scenario_path = project_root / "sia_model_scenario.json"
    scenario = {}
    if scenario_path.is_file():
        scenario = json.loads(scenario_path.read_text(encoding="utf-8"))
    selection = scenario.get("selection") or {}
    variant = str(selection.get("variant") or scenario.get("variant") or "")
    case_id = str(selection.get("case_id") or scenario.get("case_id") or "")

    der_path, observed, error = _read_rfcont(project_root)
    passed = observed is not None and abs(observed - REQUIRED_RFCONT) <= 1e-6
    if passed:
        status = "PASS_OPERATIVE_TEMPERATURE_CONTROL"
        action = "No action required. The engine input uses operative control."
    elif observed is None:
        status = "NOT_CHECKABLE"
        action = "Run ApacheSim once to generate the Apache .der input, then rerun this probe."
    else:
        status = "FAIL_AIR_OR_NON_OPERATIVE_TEMPERATURE_CONTROL"
        action = (
            "In Apache, open Settings > Building, set Control Temperature "
            "Radiant Fraction to 0.50, confirm, save the VE project, and rerun "
            "the qualified simulation."
        )

    report = {
        "schema_version": "1.0",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "status": status,
        "project": {"name": str(project.name), "path": str(project_root)},
        "scenario": {"variant": variant, "case_id": case_id},
        "engine_input": {
            "path": str(der_path) if der_path else "",
            "rfcont": observed,
            "read_error": error,
        },
        "required": {
            "rfcont": REQUIRED_RFCONT,
            "meaning": "dry-resultant/operative temperature control",
            "source": "ISO 52016-1:2017 clause 7.2.2.15; IES VE 2025 Apache Building Settings",
        },
        "action": action,
        "compliance_claim_allowed": False,
        "mutation_performed": False,
    }
    report_path = (
        project_root
        / "sia4010_artifacts"
        / "diagnostics"
        / "sia4010_test1_control_temperature_probe.json"
    )
    _write_json(report_path, report)

    print("SIA 4010 TEST 1 CONTROL-TEMPERATURE PROBE: {}".format(status))
    print("Project: {}".format(project_root))
    print("Case: {}/{}".format(variant or "<unknown>", case_id or "<unknown>"))
    print("Apache input: {}".format(der_path or "<not found>"))
    print("Observed RFCONT: {}".format(observed))
    print("Required RFCONT: 0.5 (operative/dry-resultant temperature)")
    print("Action: {}".format(action))
    print("Report: {}".format(report_path))
    print("No VE model, Apache input or APS data was changed.")
    return report


if __name__ == "__main__":
    run()
