# -*- coding: utf-8 -*-
"""Integrity of the reference data for SIA 4010 Test 1.

This file transcribes into executable assertions the manual audit recorded in
`AUDIT.md` (qa-auditor, 2026-07-30). Objective: never spend a human audit pass
on this file again. Any regeneration of
`refs/reference-data/test-1.ref.json` is re-audited here in under a second.

Two families of checks:

* **Without the source workbook** (always run, including in CI where the binaries
  of `SIA_4010_geteilter_Link/` are absent): internal consistency, node shape,
  safeguards against defects 2 and 3 from `AUDIT.md`, and the Streubereich formula
  for case 1E.
* **With the source workbook** (skipped if absent, with an explicit reason):
  value<->cell fidelity and label<->column correspondence against the real
  header rows. This second block guards against defect 1
  (column shift in Table 30).

KNOWN BLIND SPOT (measured by mutation, cf. ADR-001 §7bis): without the source
workbook, two of four corruptions go undetected — the column shift
(defect 1) and the silent conversion of an Excel error to 0. CI cannot,
as it stands, catch the class of bug that actually occurred. The planned fix is
a raw-cell fingerprint versioned in `refs/reference-data/`. Do not confuse
"CI green" and "audited data".

`openpyxl` is only used by the optional checks and remains a development / CI
dependency (it is present in VE anyway, as 3.1.2). No `import iesve`:
that is what keeps the engine testable in CI without a VE licence.

The no-f-string style is a remnant: the Python version of VEScripts has since
been measured at **3.12.3** (VE 2025, probe from 2026-07-31, ADR-001 §2).
No compatibility constraint applies anymore; this file simply does not need
to be rewritten for that.
"""

import json
import os
import re

import pytest

try:
    import openpyxl
except ImportError:  # environnement sans dependance de test
    openpyxl = None


# --------------------------------------------------------------------------
# File locations
# --------------------------------------------------------------------------

_ICI = os.path.dirname(os.path.abspath(__file__))
RACINE = os.path.abspath(os.path.join(_ICI, os.pardir, os.pardir))

# Overridable for mutation tests: we verify that these checks
# FAIL on an intentionally corrupted file (cf. docs/ADR-001 §7).
REF_JSON = os.environ.get(
    'SIA_REF_JSON',
    os.path.join(RACINE, 'refs', 'reference-data', 'test-1.ref.json'))

# Frozen raw source. Deliberately outside the repository (130 MB for the 7 workbooks):
# checks that depend on it are skipped rather than failed when it is missing.
CLASSEUR = os.environ.get(
    'SIA_TEST1_XLSX',
    os.path.join(RACINE, 'SIA_4010_geteilter_Link', 'Test1',
                 'Resultaterfassung_Test1.xlsx'))
FEUILLE = u'Zusammenfassung Testf\xe4lle'  # « Zusammenfassung Testfälle »

# Versioned raw-cell fingerprint (38 KB): substitute for the workbook
# when the frozen source is absent, typically in CI. Generated by
# `scripts/build_cell_fingerprint.py`. Without it, mutation measurement shows
# that two of four corruptions go undetected (ADR-001 §7bis).
EMPREINTE = os.environ.get(
    'SIA_TEST1_CELLS',
    os.path.join(RACINE, 'refs', 'reference-data', 'test-1.cells.json'))


# --------------------------------------------------------------------------
# Expected workbook structure
#
# Header rows and data row ranges reconstructed against the source
# and confirmed by the independent audit (`AUDIT.md`, section "What was
# VERIFIED AND CONFIRMED", pt 1). These are NOT assumptions: they are
# re-verified by `test_correspondance_libelle_colonne` whenever the workbook is
# present.
# --------------------------------------------------------------------------

GRANDEURS = {
    'sensible_heating_demand_kwh': {
        'table': 28, 'ligne_entete': 15, 'lignes_donnees': (16, 28)},
    'sensible_cooling_demand_kwh': {
        'table': 29, 'ligne_entete': 36, 'lignes_donnees': (37, 49)},
    'operative_temperature_monthly_celsius': {
        'table': 30, 'ligne_entete': 57, 'lignes_donnees': (58, 70)},
    'operative_temperature_annual_extremes_celsius': {
        'table': 32, 'ligne_entete': 104, 'lignes_donnees': (105, 107)},
    # Table 31: third pass/fail criterion for case 1E (annual hourly peak loads).
    # Added in pass 4 after the audit of the existing loader.
    'annual_hourly_peak_load_kwh': {
        'table': 31, 'ligne_entete': 81, 'lignes_donnees': (82, 83)},
}

# Exact label carried by the header of the declared column, per field.
# Recorded from the source (rows 15 / 36 / 57 / 104) on 2026-07-30.
CHAMP_VERS_ENTETE = {
    'testprogramm': 'Testprogramm',
    'iso_52016_1_2017': 'Daten Norm EN ISO 52016-1',
    'ida_ice_5_0_beta_23': 'IDA ICE',
    'excel_sia_380_2': 'EXCEL SIA 380/2',
    'energyplus_openstudio_9_1_0': 'Energy+/OpenStudio',
    'tas_edsl_9_5_2': 'EDSL-Tas',
    'mean_of_programs': 'Mittelwert',
    'range_max': 'obere Grenze',
    'range_min': 'untere Grenze',
}

# Data nodes name two fields differently from the metadata.
CHAMP_DONNEE_VERS_COLONNE = {
    'testprogramm_candidate': 'testprogramm',
    'iso_52016_1_2017_reference': 'iso_52016_1_2017',
}

# The four reference programmes that form the dispersion band for case 1E.
# Case 1E has no ISO 52016-1 column (header C15 = 'IDA ICE'), cf. AUDIT.md pt 3.
PROGRAMMES_1E = (
    'ida_ice_5_0_beta_23',
    'excel_sia_380_2',
    'energyplus_openstudio_9_1_0',
    'tas_edsl_9_5_2',
)

# Number of {value, cell} pairs measured in pass 4 (2026-07-31: 1336 in
# pass 3, + 16 for Table 31 = 2 rows x 8 columns). Safeguard against a
# regeneration that would silently lose data.
CELLULES_MINIMUM = 1352

TOLERANCE = 1e-6

_MOTIF_CELLULE = re.compile(r'^([A-Z]{1,3})([0-9]{1,5})$')


# --------------------------------------------------------------------------
# Tools
# --------------------------------------------------------------------------

def _charger_reference():
    with open(REF_JSON, encoding='utf-8') as flux:
        return json.load(flux)


@pytest.fixture(scope='module')
def reference():
    if not os.path.exists(REF_JSON):
        pytest.fail('Donnees de reference absentes : ' + REF_JSON)
    return _charger_reference()


class _SourceClasseur(object):
    """Direct access to the official workbook: the primary truth."""

    origine = 'classeur officiel'

    def __init__(self, feuille):
        self._feuille = feuille

    def valeur(self, coordonnee):
        return self._feuille[coordonnee].value

    def entete(self, ligne, colonne):
        return self._feuille[colonne + str(ligne)].value


class _SourceEmpreinte(object):
    """Access to frozen raw cells: substitute when the workbook is missing.

    Only knows the cells cited by the reference JSON and the header rows.
    An unknown address raises, rather than returning `None` — otherwise a
    check would pass through ignorance.
    """

    origine = 'empreinte figee'

    def __init__(self, donnees):
        self._cellules = donnees['cells']
        self._entetes = donnees['header_rows']

    def valeur(self, coordonnee):
        if coordonnee not in self._cellules:
            raise KeyError(
                'Cellule ' + coordonnee + " absente de l'empreinte. Relancer "
                'scripts/build_cell_fingerprint.py apres regeneration du JSON.')
        return self._cellules[coordonnee]

    def entete(self, ligne, colonne):
        return self._entetes.get(str(ligne), {}).get(colonne)


@pytest.fixture(scope='module')
def source():
    """Source of raw cells: the workbook if present, otherwise the fingerprint.

    When both are present, the fingerprint is verified AGAINST the workbook:
    it cannot drift silently and become a false witness.
    """
    empreinte = None
    if os.path.exists(EMPREINTE):
        with open(EMPREINTE, encoding='utf-8') as flux:
            empreinte = json.load(flux)

    if openpyxl is not None and os.path.exists(CLASSEUR):
        classeur = openpyxl.load_workbook(CLASSEUR, data_only=True)
        feuille = classeur[FEUILLE]
        reelle = _SourceClasseur(feuille)
        if empreinte is not None:
            derives = []
            for coordonnee, figee in empreinte['cells'].items():
                vraie = feuille[coordonnee].value
                if isinstance(figee, (int, float)) and isinstance(vraie, (int, float)):
                    if abs(float(vraie) - float(figee)) > 1e-9:
                        derives.append(coordonnee + ' : empreinte ' + repr(figee)
                                       + ', classeur ' + repr(vraie))
                elif figee != vraie:
                    derives.append(coordonnee + ' : empreinte ' + repr(figee)
                                   + ', classeur ' + repr(vraie))
            assert not derives, (
                "L'empreinte a derive du classeur ({0} cellule(s)) — relancer "
                'scripts/build_cell_fingerprint.py :\n{1}'.format(
                    len(derives), '\n'.join(derives[:10])))
        return reelle

    if empreinte is not None:
        return _SourceEmpreinte(empreinte)

    pytest.skip(
        'Ni le classeur officiel (' + CLASSEUR + ") ni l'empreinte (" + EMPREINTE
        + ') ne sont disponibles : la fidelite valeur<->cellule et la '
        'correspondance libelle<->colonne ne sont PAS verifiees.')


def _est_feuille_valeur(noeud):
    return isinstance(noeud, dict) and 'value' in noeud and 'cell' in noeud


def _decouper_cellule(ref):
    trouve = _MOTIF_CELLULE.match(ref)
    assert trouve is not None, 'Reference de cellule invalide : ' + repr(ref)
    return trouve.group(1), int(trouve.group(2))


def _iterer_enregistrements(noeud, chemin=''):
    """Yields (path, record) pairs.

    A *record* is a dict whose useful values are all leaves {value, cell}:
    one row of the SIA table (a month, a year, an extreme). `_metadata` is ignored.
    """
    if not isinstance(noeud, dict):
        return
    utiles = dict((cle, val) for cle, val in noeud.items() if cle != '_metadata')
    if utiles and all(_est_feuille_valeur(val) for val in utiles.values()):
        yield chemin, utiles
        return
    for cle, val in utiles.items():
        for item in _iterer_enregistrements(val, chemin + '/' + cle):
            yield item


def _iterer_feuilles(reference):
    for grandeur, cas_tous in reference['reference_values'].items():
        for cas, noeud in cas_tous.items():
            for chemin, enreg in _iterer_enregistrements(noeud):
                for champ, feuille_valeur in enreg.items():
                    yield grandeur, cas, chemin, champ, feuille_valeur


def _proche(gauche, droite, tolerance=TOLERANCE):
    return abs(gauche - droite) <= tolerance


def _colonnes_declarees(noeud_cas):
    return noeud_cas.get('_metadata', {}).get('columns', {})


# --------------------------------------------------------------------------
# 1. Structural checks — without the source workbook
# --------------------------------------------------------------------------

def test_grandeurs_attendues_presentes(reference):
    """The four audited tables are present. A disappearance must break the build."""
    presentes = set(reference['reference_values'].keys())
    attendues = set(GRANDEURS.keys())
    manquantes = attendues - presentes
    assert not manquantes, 'Grandeurs absentes du JSON : ' + repr(sorted(manquantes))


def test_forme_des_feuilles_de_valeur(reference):
    """Each leaf carries a value, a unit and a valid cell reference."""
    fautifs = []
    for grandeur, cas, chemin, champ, feuille_valeur in _iterer_feuilles(reference):
        localisation = '/'.join([grandeur, cas, chemin.strip('/'), champ])
        if 'unit' not in feuille_valeur:
            fautifs.append(localisation + ' : unite absente')
        valeur = feuille_valeur['value']
        if valeur is not None and not isinstance(valeur, (int, float)):
            fautifs.append(localisation + ' : valeur non numerique ' + repr(valeur))
        _decouper_cellule(feuille_valeur['cell'])
    assert not fautifs, 'Feuilles mal formees :\n' + '\n'.join(fautifs)


def test_volume_de_donnees_non_regresse(reference):
    """A regeneration must not silently lose cells."""
    total = sum(1 for _ in _iterer_feuilles(reference))
    assert total >= CELLULES_MINIMUM, (
        'Regression de volume : {0} cellules extraites contre {1} auditees le '
        '2026-07-30. Si la reduction est deliberee, mettre a jour '
        'CELLULES_MINIMUM en le justifiant.'.format(total, CELLULES_MINIMUM))


def test_valeurs_nulles_documentees(reference):
    """A null value comes from an Excel error cell: it must carry a note.

    AUDIT.md pt 7: no Excel error must be silently converted to 0.
    A mandatory note makes silent conversion impossible to hide.
    """
    sans_note = []
    for grandeur, cas, chemin, champ, feuille_valeur in _iterer_feuilles(reference):
        if feuille_valeur['value'] is None and not feuille_valeur.get('note'):
            sans_note.append('/'.join([grandeur, cas, chemin.strip('/'), champ])
                             + ' (' + feuille_valeur['cell'] + ')')
    assert not sans_note, (
        'Valeurs nulles sans note explicative :\n' + '\n'.join(sans_note))


def test_enregistrement_sur_une_seule_ligne(reference):
    """All cells of a record share the same Excel row.

    Safeguard against a row shift: a month cannot mix values taken from
    two different rows.
    """
    fautifs = []
    for grandeur, cas_tous in reference['reference_values'].items():
        for cas, noeud in cas_tous.items():
            for chemin, enreg in _iterer_enregistrements(noeud):
                lignes = set(_decouper_cellule(f['cell'])[1] for f in enreg.values())
                if len(lignes) != 1:
                    fautifs.append('{0}/{1}{2} : lignes {3}'.format(
                        grandeur, cas, chemin, sorted(lignes)))
    assert not fautifs, 'Enregistrements a cheval sur plusieurs lignes :\n' + \
        '\n'.join(fautifs)


def test_lignes_dans_la_plage_de_leur_table(reference):
    """The cited cells fall within the data range of the relevant table."""
    fautifs = []
    for grandeur, cas_tous in reference['reference_values'].items():
        if grandeur not in GRANDEURS:
            continue
        debut, fin = GRANDEURS[grandeur]['lignes_donnees']
        for cas, noeud in cas_tous.items():
            for chemin, enreg in _iterer_enregistrements(noeud):
                for champ, feuille_valeur in enreg.items():
                    _, ligne = _decouper_cellule(feuille_valeur['cell'])
                    if not (debut <= ligne <= fin):
                        fautifs.append('{0}/{1}{2}/{3} : {4} hors plage {5}-{6}'.format(
                            grandeur, cas, chemin, champ,
                            feuille_valeur['cell'], debut, fin))
    assert not fautifs, 'Cellules hors de la plage de leur table :\n' + \
        '\n'.join(fautifs)


def test_colonnes_des_donnees_conformes_aux_metadonnees(reference):
    """The column of each cell corresponds to the column declared for its field.

    First half of the safeguard against DEFECT 1 from `AUDIT.md`: the JSON must
    not contradict itself. The second half (the real label of the column) requires
    the workbook, cf. `test_correspondance_libelle_colonne`.
    """
    fautifs = []
    for grandeur, cas_tous in reference['reference_values'].items():
        for cas, noeud in cas_tous.items():
            declarees = _colonnes_declarees(noeud)
            if not declarees:
                fautifs.append(grandeur + '/' + cas + ' : aucune colonne declaree')
                continue
            for chemin, enreg in _iterer_enregistrements(noeud):
                for champ, feuille_valeur in enreg.items():
                    cle = CHAMP_DONNEE_VERS_COLONNE.get(champ, champ)
                    if cle not in declarees:
                        fautifs.append('{0}/{1}{2} : champ {3} non declare dans '
                                       '_metadata.columns'.format(
                                           grandeur, cas, chemin, champ))
                        continue
                    colonne, _ = _decouper_cellule(feuille_valeur['cell'])
                    if colonne != declarees[cle]:
                        fautifs.append(
                            '{0}/{1}{2}/{3} : cellule en colonne {4} mais '
                            '_metadata declare {5}'.format(
                                grandeur, cas, chemin, champ,
                                colonne, declarees[cle]))
    assert not fautifs, ('Incoherences colonne donnee <-> metadonnees :\n' +
                         '\n'.join(fautifs))


def test_table_32_ne_contient_que_les_cas_flottement_libre(reference):
    """Safeguard against DEFECT 2 from `AUDIT.md`.

    Table 32 (annual operative temperature extremes, compact zone
    rows 105-107) contains only two blocks: 600FF (B-G) and 900FF (J-O).
    Entries '600' and '640' were mis-labelled duplicates. Physical proof:
    a maximum of 63.5 degrees and a minimum of -16.9 belong only to a
    free-floating case.
    """
    cas = set(reference['reference_values'][
        'operative_temperature_annual_extremes_celsius'].keys())
    assert cas == {'600FF', '900FF'}, (
        "Table 32 doit contenir exactement {'600FF', '900FF'} ; trouve " +
        repr(sorted(cas)) + ". Les cas chauffes/refroidis ne figurent pas dans "
        "cette table (cf. AUDIT.md defaut n^2).")


def test_donnees_manquantes_ne_contredisent_pas_le_contenu(reference):
    """Safeguard against DEFECT 3 from `AUDIT.md`.

    `data_missing` must not declare missing a table that has nonetheless been extracted.
    """
    extraites = set(reference['extraction_completeness']['tables_extracted'])
    contradictions = []
    for cle, texte in reference.get('data_missing', {}).items():
        numeros = set(int(n) for n in re.findall(r'\d{2}', cle + ' ' + str(texte)))
        recouvrement = numeros & extraites
        if recouvrement:
            contradictions.append('data_missing[' + cle + '] mentionne la/les '
                                  'table(s) ' + repr(sorted(recouvrement)) +
                                  ' pourtant listee(s) comme extraite(s)')
    assert not contradictions, '\n'.join(contradictions)


def test_cas_declares_correspondent_au_contenu(reference):
    """`extraction_completeness.cases_covered` must reflect the cases actually present."""
    declares = set(reference['extraction_completeness']['cases_covered'])
    reels = set()
    for cas_tous in reference['reference_values'].values():
        reels |= set(cas_tous.keys())
    fantomes = declares - reels
    non_declares = reels - declares
    assert not fantomes, 'Cas declares mais absents : ' + repr(sorted(fantomes))
    assert not non_declares, 'Cas presents mais non declares : ' + \
        repr(sorted(non_declares))


# --------------------------------------------------------------------------
# 2. Pass/fail criterion for case 1E — the only verdict rule of Test 1
#
# `Spezifikation_Test1.pdf`, section Testkriterien: only case 1E carries an
# acceptance criterion (dispersion band). Cases 600/640/900/940/600FF/900FF
# have none (cf. traceability/test-1.spec.md §6).
# --------------------------------------------------------------------------

def _enregistrements_1e(reference, grandeur):
    noeud = reference['reference_values'][grandeur]['1E']
    return list(_iterer_enregistrements(noeud))


def test_1e_moyenne_est_la_moyenne_arithmetique(reference):
    """`Mittelwert` = arithmetic mean of the 4 reference programmes."""
    verifies = 0
    for grandeur in ('sensible_heating_demand_kwh', 'sensible_cooling_demand_kwh'):
        for chemin, enreg in _enregistrements_1e(reference, grandeur):
            valeurs = [enreg[p]['value'] for p in PROGRAMMES_1E]
            if any(v is None for v in valeurs):
                continue
            attendue = sum(valeurs) / float(len(valeurs))
            obtenue = enreg['mean_of_programs']['value']
            assert _proche(obtenue, attendue), (
                '{0}/1E{1} : Mittelwert {2} != moyenne des programmes {3}'.format(
                    grandeur, chemin, obtenue, attendue))
            verifies += 1
    assert verifies >= 26, ('Seulement {0} periodes verifiees ; 26 attendues '
                            '(12 mois + annuel, chaud + froid).'.format(verifies))


def test_1e_plage_de_dispersion(reference):
    """`obere/untere Grenze` = symmetric band around the mean, floor at 0.

    CORRECTION OF A MISCONCEPTION established by the audit (AUDIT.md pt 4): the
    Streubereich is NOT the min/max of the programmes. The real workbook formula is

        ecart_max = max |programme - mean|
        range_max = mean + ecart_max
        range_min = max(0, mean - ecart_max)

    Verified 26/26. This test exists so that the engine never implements the
    wrong version: it defines the pass/fail criterion for case 1E.
    """
    verifies = 0
    for grandeur in ('sensible_heating_demand_kwh', 'sensible_cooling_demand_kwh'):
        for chemin, enreg in _enregistrements_1e(reference, grandeur):
            valeurs = [enreg[p]['value'] for p in PROGRAMMES_1E]
            if any(v is None for v in valeurs):
                continue
            moyenne = sum(valeurs) / float(len(valeurs))
            ecart_max = max(abs(v - moyenne) for v in valeurs)
            attendu_max = moyenne + ecart_max
            attendu_min = max(0.0, moyenne - ecart_max)
            obtenu_max = enreg['range_max']['value']
            obtenu_min = enreg['range_min']['value']
            assert _proche(obtenu_max, attendu_max), (
                '{0}/1E{1} : obere Grenze {2} != {3}'.format(
                    grandeur, chemin, obtenu_max, attendu_max))
            assert _proche(obtenu_min, attendu_min), (
                '{0}/1E{1} : untere Grenze {2} != {3}'.format(
                    grandeur, chemin, obtenu_min, attendu_min))
            verifies += 1
    assert verifies >= 26, ('Seulement {0} periodes verifiees ; 26 attendues.'
                            .format(verifies))


def test_1e_moyenne_dans_sa_propre_plage(reference):
    """Physical consistency: the mean always falls within the dispersion band."""
    for grandeur in ('sensible_heating_demand_kwh', 'sensible_cooling_demand_kwh'):
        for chemin, enreg in _enregistrements_1e(reference, grandeur):
            moyenne = enreg['mean_of_programs']['value']
            borne_min = enreg['range_min']['value']
            borne_max = enreg['range_max']['value']
            if None in (moyenne, borne_min, borne_max):
                continue
            assert borne_min - TOLERANCE <= moyenne <= borne_max + TOLERANCE, (
                '{0}/1E{1} : moyenne {2} hors de [{3}, {4}]'.format(
                    grandeur, chemin, moyenne, borne_min, borne_max))


# --------------------------------------------------------------------------
# 3. Checks against the frozen source — skipped if the workbook is absent
# --------------------------------------------------------------------------

def test_fidelite_valeur_cellule(reference, source):
    """Each stored value is exactly that of the cited Excel cell.

    This is the central audit check: 1336/1336 concordances on 2026-07-30.
    A null value must correspond to a non-numeric cell (Excel error such as
    #DIV/0! or #REF!), never to an invented zero.
    """
    divergences = []
    total = 0
    for grandeur, cas, chemin, champ, feuille_valeur in _iterer_feuilles(reference):
        total += 1
        attendue = feuille_valeur['value']
        localisation = '/'.join([grandeur, cas, chemin.strip('/'), champ]) + \
            ' (' + feuille_valeur['cell'] + ')'
        try:
            obtenue = source.valeur(feuille_valeur['cell'])
        except KeyError:
            # Cell unknown to the fingerprint: either the JSON cites a cell
            # it did not cite before (column shift), or the fingerprint has not
            # been regenerated. Both must fail, not pass.
            divergences.append(localisation + " : cellule absente de la source "
                               "(" + source.origine + ")")
            continue
        if attendue is None:
            if isinstance(obtenue, (int, float)):
                divergences.append(localisation + ' : JSON null mais la cellule '
                                   'porte le nombre ' + repr(obtenue))
        elif not isinstance(obtenue, (int, float)):
            divergences.append(localisation + ' : JSON ' + repr(attendue) +
                               ' mais la cellule porte ' + repr(obtenue))
        elif not _proche(float(obtenue), float(attendue)):
            divergences.append(localisation + ' : JSON ' + repr(attendue) +
                               ' != Excel ' + repr(obtenue))
    assert not divergences, ('{0} divergence(s) sur {1} cellules :\n{2}'.format(
        len(divergences), total, '\n'.join(divergences[:40])))


def test_correspondance_libelle_colonne(reference, source):
    """Each declared column carries, in the real header, the claimed label.

    Second half of the safeguard against DEFECT 1 from `AUDIT.md`: this is
    exactly the check that revealed 286 inconsistencies in Table 30 for
    cases 600/640/900/940 (data shifted by one column, EDSL-Tas lost).
    """
    divergences = []
    for grandeur, cas_tous in reference['reference_values'].items():
        if grandeur not in GRANDEURS:
            continue
        ligne_entete = GRANDEURS[grandeur]['ligne_entete']
        for cas, noeud in cas_tous.items():
            for champ, colonne in _colonnes_declarees(noeud).items():
                if champ not in CHAMP_VERS_ENTETE:
                    divergences.append('{0}/{1} : champ inconnu {2}'.format(
                        grandeur, cas, champ))
                    continue
                attendu = CHAMP_VERS_ENTETE[champ]
                cellule = colonne + str(ligne_entete)
                obtenu = source.entete(ligne_entete, colonne)
                if obtenu is None or str(obtenu).strip() != attendu:
                    divergences.append(
                        '{0}/{1}/{2} : colonne {3}, en-tete {4} = {5!r} '
                        'au lieu de {6!r}'.format(grandeur, cas, champ, colonne,
                                                  cellule, obtenu, attendu))
    assert not divergences, ('{0} incoherence(s) libelle <-> colonne :\n{1}'.format(
        len(divergences), '\n'.join(divergences[:40])))


def test_source_declaree_est_la_source_utilisee(reference, source):
    """The sheet cited in the JSON is the one that was actually read."""
    declaree = reference['excel_source']['sheet']
    assert declaree == FEUILLE, (
        'Le JSON declare la feuille ' + repr(declaree) + ' mais les controles '
        'portent sur ' + repr(FEUILLE))


def test_empreinte_couvre_toutes_les_cellules_citees(reference):
    """The fingerprint must follow the JSON, otherwise CI goes blind again.

    A JSON regeneration citing new cells without regenerating the fingerprint
    would leave those cells unchecked in CI. We forbid this explicitly rather
    than discovering it later.
    """
    if not os.path.exists(EMPREINTE):
        pytest.skip('Empreinte absente : ' + EMPREINTE)
    with open(EMPREINTE, encoding='utf-8') as flux:
        empreinte = json.load(flux)
    citees = set(f['cell'] for _g, _c, _p, _ch, f in _iterer_feuilles(reference))
    manquantes = citees - set(empreinte['cells'])
    assert not manquantes, (
        '{0} cellule(s) citees par le JSON mais absentes de l empreinte. '
        'Relancer scripts/build_cell_fingerprint.py. Exemples : {1}'.format(
            len(manquantes), sorted(manquantes)[:10]))
